version: "3.8"

services:

  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3310:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lista
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    build: "./back"
    container_name: node-container
    restart: always
    ports: 
      - "3001:3001"
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=lista
      - DB_PORT=3306
    depends_on:
      - db
  
  web:
    build: "./front"
    container_name: react-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api